CREATE TABLE users (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email varchar(255) NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE posts (
   id SERIAL PRIMARY KEY,
   names varchar(255),
   description TEXT,
   min_price int,
   currency_price int,
   photos bytea,
   status boolean,
   user_id int REFERENCES users(id)
);